global:
  scrape_interval:     30s

scrape_configs:
  - job_name: jmxexporter
    consul_sd_configs:
        - server: localhost:8500
          services:
           - jmxexporter
  - job_name: telegraf
    consul_sd_configs:
        - server: localhost:8500
          services:
           - telegraf